_SELECTED_SHIELD = _CONST_SHIELD_SCALE

_UC_IO_SCALE_CLOCK_PIN = 4
_UC_IO_SCALE_DATA_PIN = 5
_UC_IO_SCALE_SPI_PIN = 8

_UC_IO_WEIGHT_ON = 6
_UC_IO_TEMP_SENSOR = 7

_UC_IO_LED_1_ON = 11
_UC_IO_LED_2_ON = 17

_UC_IO_RFID_READER_TX = 41
_UC_IO_RFID_READER_RX = 42

_UC_IO_TARE_BTN = 2
_UC_IO_BUZZER_ON = 1
