_SELECTED_SHIELD = _CONST_SHIELD_ADVIND

""" SDI-12 """
_UC_IO_RCV_OUT = 41
_UC_IO_DRV_ON = 11
_UC_IO_RCV_ON = 1
_UC_IO_DRV_IN = 17
_UC_IO_SNSR_REG_ON = 37
_UC_IO_PWR_SDI_SNSR_1_ΟΝ = 42
_UC_IO_PWR_SDI_SNSR_2_ΟΝ = 48


""" 4-20mA """
_UC_IO_CUR_SNS_ON = 9
_CUR_SNSR_OUT_1 = 4
_CUR_SNSR_OUT_2 = 5
_UC_IO_SNSR_GND_4_20_SNSR_1_ΟΝ = 7
_UC_IO_SNSR_GND_4_20_SNSR_2_ΟΝ = 8
_INA_GAIN = 100
_SHUNT_OHMS = 0.47

""" Pulse counter """
UC_IO_DGTL_SNSR_READ = 2

""" Chip ID """
_I2C_CHIP_ID_ADDRESS = 0x54
